### ISSUE TITLE
pyzillow.pyzillowerrors.ZillowError: Status 6: This account is not authorized to execute this API call.

### ISSUE THREAD

**Issue by sansreddy** [hanneshapke/pyzillow#40]
In my zillow account settings, i have 4 API selections and I have selected the below 3.
Directory API
Profile Summary API
Reviews API.

but then, I get the below error. Appreciate any help.

Traceback (most recent call last):
  File "zillowRapid.py", line 8, in <module>
    deep_search_response = zillow_data.get_deep_search_results(address,zipcode,False)
  File "/Users/sanjayreddy/opt/anaconda3/lib/python3.7/site-packages/pyzillow/pyzillow.py", line 77, in get_deep_search_results
    return self.get_data(url, params)
  File "/Users/sanjayreddy/opt/anaconda3/lib/python3.7/site-packages/pyzillow/pyzillow.py", line 133, in get_data
    raise ZillowError(int(response.findall("message/code")[0].text))
pyzillow.pyzillowerrors.ZillowError: Status 6: This account is not authorized to execute this API call.

**Comment by cstrouse** [comment]
@sansreddy It looks like Zillow closed down the API a few months ago.

**Comment by RylanSchaeffer** [comment]
Seriously? Their website suggests one can still access their results

https://www.zillow.com/howto/api/GetSearchResults.htm

**Comment by RylanSchaeffer** [comment]
@cstrouse how do you know Zillow shut down the API?

**Comment by YukunYangNPF** [comment]
Are there any updates about this? I'm facing the same issue.

**Comment by youssefabdelwahab** [comment]
is there any update on this guy , need to know ASAP for a project

**Comment by jsevilla274** [comment]
@youssefabdelwahab it seems the Zillow API has been down for a while, see this thread for more info https://github.com/hanneshapke/pyzillow/issues/22#issuecomment-663772197
